apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amateurs

resources:
  - mysql-master-config.yaml
  - mysql-master-pvc.yaml
  - mysql-master-statefulset.yaml
  - mysql-master-service.yaml
