apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: amateurs
data:
  my.cnf: |
    [mysqld]
    authentication_policy=mysql_native_password
    bind-address=0.0.0.0
    server-id=1
    log-bin=mysql-bin
    gtid-mode=ON
    enforce-gtid-consistency=ON
    log_replica_updates=ON
    read-only=OFF
    super-read-only=OFF
    max_connections=200
    innodb_buffer_pool_size=512M
    innodb_redo_log_capacity=536870912
    innodb_flush_log_at_trx_commit=1
    sync_binlog=1
    binlog_expire_logs_seconds=604800
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
