apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: amateurs
spec:
  serviceName: mysql-master-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
        role: master
    spec:
      containers:
      - name: mysql-master
        image: mysql:8.0.43
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-master-storage
          mountPath: /var/lib/mysql
        - name: mysql-master-config
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: mysql-master-storage
        persistentVolumeClaim:
          claimName: mysql-master-storage
      - name: mysql-master-config
        configMap:
          name: mysql-master-config
