apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
  namespace: amateurs
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    max_connections=200
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    innodb_buffer_pool_size=512M
    read-only=ON
    super-read-only=ON
