apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  namespace: amateurs
spec:
  serviceName: mysql-slave-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
        role: slave
    spec:
      containers:
      - name: mysql-slave
        image: mysql:8.0.43
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-slave-storage
          mountPath: /var/lib/mysql
        - name: mysql-slave-config
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
            - -e
            - "SELECT 1"
          initialDelaySeconds: 10
          timeoutSeconds: 1
      volumes:
      - name: mysql-slave-storage
        persistentVolumeClaim:
          claimName: mysql-slave-storage
      - name: mysql-slave-config
        configMap:
          name: mysql-slave-config
      initContainers:
      - name: wait-for-master
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mysql-master 3306; do echo waiting for mysql master; sleep 5; done;']
