apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: amateurs
spec:
  selector:
    app: mysql-slave
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-headless
  namespace: amateurs
spec:
  selector:
    app: mysql-slave
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: amateurs
spec:
  selector:
    role: slave
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
