apiVersion: v1
kind: Service
metadata:
  name: amateurs
  namespace: amateurs
spec:
  sessionAffinity: ClientIP
  selector:
    app: amateurs
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
